services:
    db:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user"]
            interval: 10s
            timeout: 5s
            retries: 5

    server:
        build:
            context: .
            dockerfile: dockerfile
        container_name: ms
        env_file:
            - .env.production
        ports:
            - "5000:5000"
        depends_on:
            db:
                condition: service_healthy
